#!/bin/sh
set -eu

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS \`$MYSQL_APP_DATABASE\`;

CREATE USER IF NOT EXISTS '$MYSQL_APP_USER'@'%' IDENTIFIED BY '$MYSQL_APP_PASSWORD';
CREATE USER IF NOT EXISTS '$MYSQL_ADMIN_USER'@'%' IDENTIFIED BY '$MYSQL_ADMIN_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE ON \`$MYSQL_APP_DATABASE\`.* TO '$MYSQL_APP_USER'@'%';
GRANT CREATE ON *.* TO '$MYSQL_ADMIN_USER'@'%';

FLUSH PRIVILEGES;
SQL
