#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "$POSTGRES_APP_DB";

CREATE USER "$POSTGRES_APP_USER" WITH PASSWORD '$POSTGRES_APP_PASSWORD';
CREATE USER "$POSTGRES_ADMIN_USER" WITH PASSWORD '$POSTGRES_ADMIN_PASSWORD' CREATEDB;

GRANT CONNECT ON DATABASE "$POSTGRES_APP_DB" TO "$POSTGRES_APP_USER";
GRANT CONNECT ON DATABASE "$POSTGRES_APP_DB" TO "$POSTGRES_ADMIN_USER";

\connect "$POSTGRES_APP_DB"

GRANT USAGE ON SCHEMA public TO "$POSTGRES_APP_USER";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$POSTGRES_APP_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$POSTGRES_APP_USER";
SQL
